---
title: "Dissertation drafts and notes"
author: "Sven Kasser"
date: "06/07/2021"
output: 
  pdf_document:
citation_package: natbib
bibliography: Dissertation.bib
biblio-style: bath
---

# 1. Introduction

Insert a more general intro to the dissertation - to be written latter.

Inspiration:

Marriage is a human universal that unites males and females in socially-recognized reproductive units [[1]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0019066#pone.0019066-Murdock1). While stable-breeding bonds are found in numerous taxa, human marriages have wide significance beyond reproduction. Marriage is a fundamental cornerstone of human economic, social, and kinship networks [[1]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0019066#pone.0019066-Murdock1)--[[6]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0019066#pone.0019066-Alexander1). Indeed, marriage as an elementary principle of human kinship systems has long been considered a central aspect of between-group alliances [[5]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0019066#pone.0019066-LeviStrauss1).

## 1.1. Sexual selection theory and human mating strategies

**The Darwin-Bateman paradigm.** Until a relatively recent diversification of approaches, sexual selection theory has long been used to assert that sexually antagonistic selection on interest in mating may give rise to a fundamental and near-universal dichotomy between "coy females" and "promiscuous males" - sometimes characterised as the "Darwin-Bateman paradigm" [@borgerhoffmulder2021; @dewsbury2005]. As the name would suggest, it is rooted in @darwin1981 's early assertion that males in almost all animal species are more eager and less discriminate than females when it comes to reproduction. This, Darwin continues, makes them the primary target of evolution via sexual selection - either through male-male competition or through female choice, the inverse processes of which (e.g. female-female competition, etc.) he largely neglects [but see @bonduriansky2009]. Darwin, of course, could only speculate about the origin of these sex differences, which he tentatively reasoned to be driven by the fact that insemination requires males to closely approach females, thus selecting for an "eagerness" in males to seek out the opposite sex [@darwin1981]. But the brevity with which this, entirely non-empirical, explanation is offered in The Descent of Man perhaps speaks to the lack of confidence Darwin had in this line of reasoning. In any case, Darwin's ideas on sexual selection and the associated coy female-ardent male dichotomy largely languished in scientific no-man's land until the latter half of the eponymous paradigm, Angus J. Bateman, published an article titled "Intra-sexual selection in Drosophila" in Heredity in 1948. Here, @bateman1948 publishes three key findings that would prove very influential for the science of mating systems: For one, he found that males show greater variability in fertility or "reproductive success" than females across his experiments. Similarly, mating success in males was significantly more variable than mating success in females. This held both on a group level, with 1 in 5 males failing to reproduce where for females, it was only 1 in 25, as well as on the individual level, where number of partners varied more between individual males than between individual females. The third finding was that, additionally, reproductive success of males seemed to increase linearly with number of mates - indicating that males should strictly prefer more mating opportunities (i.e. promiscuity), within the constraints of Bateman's experiments. Female reproductive success, on the other hand, did not seem to benefit from additional mates beyond the first one. When visualised as a two-dimensional line graph, this relationship between number of mates (or "mating success") and reproductive success is referred to as Bateman's gradient, the slope of which, after Bateman, is often posited to be steeper for males than for females [@gerlach2012]. Collectively, Bateman's results were enshrined in modern sexual-selection research as "Bateman's principles", seemingly offering an elegant explanation for sex differences in sexual selection that had eluded Darwin [@arnold1994], and which continue to exert considerable influence on contemporary sexual selection research [e.g. @janicke2016]. @bateman1948 explained these results by invoking anisogamy: Male sex cells (gametes) are comparatively small and metabolically inexpensive, making the number of matings the limiting factor of male reproductive success, whereas female gametes are expensive and thus themselves constitute the limiting factor on female reproduction. Like his results, the idea of anisogamy as an underlying cause was later picked up by @trivers1972, who in his landmark chapter on parental investment (cited 15940 times according to Google Scholar) argued that sex differences in post-zygotic parental investment (i.e. parental care) followed logically from anisogamy, which he recognises as a form of pre-zygotic parental investment itself. Subsequently, in circumstances under which males and females differ in their parental investment, they ought to differ in their reproductive strategies, with the least invested sex being more promiscuous [@trivers1972]. Simply put, their relatively small parental investment affords males with a higher potential reproductive rate, which should bias them toward promiscuous mating [@clutton-brock1991]. Interestingly, invoking anisogamy as the ultimate cause for sex-differences in mating behaviour poses the corollary question of what, ultimately, causes anisogamy, which similarly has been subject of much scientific interest, notably by Geoff Parker and researcher influenced by him [@parker1972; @lehtonen2011]. This is why the aforementioned "Darwin-Bateman paradigm" is sometimes more completely, but rather confusingly, described as the "Darwin-Bateman-Trivers-Parker paradigm" of sexual selection and the evolution of sex roles [@hoquet2020]. This paradigm, or derivations thereof, remains at the basis of much sexual-selection research in non-human animals [e.g. @arnold1994; @clutton-brock2019].

It is worth noting that, in his original paper, @bateman1948 himself only alludes in passing to generalising his results to humans, though he seemed convinced that his results would extend to many species in which anisogamy holds. Similarly, while @trivers1972 is more explicit in terms of applying his parental investment principles to humans, overall he also takes a broad, cross-specific view of the subject. Nevertheless, and albeit firmly rooted in theoretical evolutionary biology, Trivers' treatment of Bateman's ideas quickly captured the interest of evolutionary minded anthropologists and psychologists, first through inclusion in Wilson's Sociobiology [@wilson1975] and the subsequently growing focus on evolutionary causation of behaviour, and then later through the prominent early work of evolutionary psychologists focused on human mating behaviour [e.g. @buss1989]. For example, in their seminal work on sex differences in mating strategies, @buss1993 argue, in line with Trivers, that obligatory parental investment differences are a fundamental evolutionary driver in human male preferences for promiscuous (short-term) mating. In this context, they also contend that the broad preferences of males for multiple partners, in the context of polygamy, similarly evolved as a function of the same sex differentials. Since then, evolutionary psychologists have gathered a substantial amount of evidence for consistent sex-differences in reproductive strategies, sometimes labelled the males compete-females choose (MCFC) model, across geographies [e.g. @chang2011; @souza2016] and methodologies [e.g. @conroy-beam2015; @thomas2020], broadly along the lines of Trivers' original sex-specific predictions. In this manner, sexual selection theory-derived work on evolved human mating strategies continues as a fruitful (one may be tempted to say "fertile") field of ongoing research [@buss2019; @mogilski2021], albeit an often contentious one [@stewart-williams2013; @eagly1999; @zentner2012]. In an adjacent but separate line of research, Bateman's principles have been directly put to the empirical test with human populations [reviewed in @betzig2012]. The sex differences in variance of reproductive success in this context are often associated with the cultural practice of polygyny, which allows for large differentials in reprodutive success among males via varying number of partners [@low1988]. There are significant difficulties in compiling data on reproductive success in humans, for example because paternity is particularly challenging to discern in the absence of comprehensive genetic testing - nevertheless anthropologists, demographers, and occasionally historians have collected a wealth of cross-cultural data on reproductive success by sex [@betzig2012; @brown2009]. On the matter of Bateman's principles, @brown2009 report that while there is some good evidence that reproductive success is more variable in males than females overall across multiple datasets, seemingly affirming Bateman's first principle, this difference is neither universal nor constant. For example, in data on the Meriam people of Australia, variance of reproductive success in women is twice as high as that in men, running directly counter to Bateman's first principle [@smith2003]. Similarly, @brown2009 contend that, contrary to a widely-held assumption among evolutionary-minded behavioural scientists, the widespread practice of polygyny does not necessarily indicate greater variation in mating success (Bateman's second principle) among males than females, a criticism to which I will return in the next section. Overall, the Darwin-Bateman paradigm has certainly been a dominant and driving theoretical narrative in the evolutionary investigation of human sex roles across both evolutionary psychological and behavioural ecological approaches, and, as I will explore in later sections, sits at the base of many evolutionary approaches to human marriage systems as well.

**Recent critiques and a new sexual selection paradigms.** But recent advances across multiple disciplines have cast reasonable doubt on the clear applicability of Bateman's principles to humans, or at least imply that the coy female-ardent male dichotomy requires substantial additional nuance. These critiques generally span three categories - theoretical advancements in parental investment and sexual selection theory, empirical critiques of Bateman and Triver's original work, and methodological difficulties in applying Bateman's principles to humans specifically. I will discuss each in turn.

First off, the factors influencing strength and direction of sexual selection have been subject to recent theoretical revisions. @kokko2008 question two key features of Trivers' reasoning on sex role divergence, which they describe as the "female" and "male" argument, respectively. The female argument relates to the poorly substantiated claim that pre-zygotic investment (anisogamy) necessarily leads to post-zygotic parental care. Fundamentally, however, this association does not strictly hold, as past investment in offspring should be irrelevant, in principle, to decisions regarding to future care - the cost of anisogamy is unrecoverable, and evolution should favour the care decision with the highest future payoff [@dawkins1976a]. It is not immediately obvious why female's future payoff from parental care should be higher than male's, and whether past investment reduces the cost or increases the benefits of future care is uncertain [@kokko2008]. The "male argument" relates to the idea that if effort or time are limited resource, and intra-sexual competition for mates is higher in males than in females, this necessarily leads to more investment in competition in males at the cost of parental care. However, @fromhage2005 have suggested that strong male-male competition may actually favour monogamous mating (as the mate search cost in this scenario may be very high). Overall, it is clearly worth considering under what circumstances the marginal benefit of care may outstrip the marginal benefit of competition, thus favouring male parental care[@kokko2008]. Overall, @kokko2008 question the straightforward relationship between anisogamy and choosiness/promiscuity expounded on by Trivers. In a related piece of work, theoretical modelling indicates that rather than anisogamy alone, sex-specific mortality cost of caring, sex-specific mortality cost of mate searching, mate encounter rate, variation in mate quality, and the operational sex ratio (which will be discussed in greater detail in the next section) all seem to be important parameters in determining the strength and direction of sexual selection, and the associated choosiness it engenders [@kokko2001]. Notably, anisogamy may well factor into some of these elements, but the exact mechanisms by which it does requires a nuanced understanding of all implicated parameters. Thus, broadly, these models seek to extend and refine rather than replace existing models of sexual selection and parental investment. A more forceful variation of this critique, which discounts the causal role of anisogamy entirely, is advanced by some evolutionary biologists who argue that the use of "sex roles" in this line of research is inherently problematic (given their non-continuous nature and variability across taxa), and dismiss inherent sex differences in favour of environmental and/or stochastic effects which lead to flexible "sex-typical" (in the intraspecific sense) behaviours [@gowaty2009; @ah-king2013]. For reference, @ah-king2013a offer a useful review of this perspective [but see @kokko2013], a detailed discussion of which would, however, exceed the scope of this introduction.

Outside of these theoretical refinements, there have been specific empirical challenges to Bateman's principles, both via reexamination of his original experiments and their conceptual replication across taxa [see @tang-martinez2016 for a review]. Multiple scholars have extensively criticised Bateman's experimental design and procedure [@dewsbury2005; @tang-martinez2005], with specific criticisms spanning selective use of data [@tang-martinez2005], choice of species and sample size [@hoquet2020], statistical technique and inference [@sutherland1985; @snyder2007], and systematic mismeasurement of fitness variance [@gowaty2012]. Of particular note here is a full-scale replication of Bateman's experiments which revealed flaws in Bateman's measurement of mating and reproductive success, both of which are crucial to the formulation of his principles [@gowaty2012; @gowaty2013]. A more conceptual challenge to the Darwin-Bateman paradigm is the repeated evidence of multiple female matings and polyandry across multiple taxa including primates [e.g. @newcomer1999; @drea2005; @lewis2004]. In line with these observations, empirical work has also demonstrated that females may benefit from polyandry, counter to some of Bateman's conclusions [@slatyer2012; but see @akcay2007]. Additionally, the overarching finding that sexual selection may strongly target females, and that male mate choice can play a significant evolutionary role is now largely uncontroversial among evolutionary biologists, even those who advocate for the usefulness and general validity of Bateman's principles [@clutton-brock2009; @clutton-brock2013; @janicke2016]. The issue remains, however, that much of this nuance is often lost in discussions of Bateman's principles outside of evolutionary biology [e.g. the evolutionary psychology approaches discussed above; @borgerhoffmulder2021]. Overall, all this empirical criticism tends to coalesce into one suggestion; that it is perhaps more fruitful to examine the Darwin-Bateman paradigm on a species-by-species basis, rather than applying it indiscriminately to the entirety of biology [@tang-martinez2016].

Fortunately, evolutionary anthropologists are afforded to do just that. But even among humans specifically, application of Bateman's principles runs into some challenges. One would be remiss not the mention the contribution that Sarah Blaffer Hrdy has made in challenging the application of static, Bateman-derived sex roles in human and non-human primates [@hrdy1981]. In line with aforementioned empirical challenges, @hrdy1986 discusses at length evidence for polyandrous mating in primates, including barbary macaques, baboons and langurs, and challenges the uncritical extension of Bateman's results. Clearly, Bateman's principles within human populations, too, are subject to a range of interacting factors discussed in the theoretical approaches above, which render unitary mating strategies in humans counter-intuitive - as exemplified by the diversity of human mating systems codified via different marriage norms and practices [@fortunato2018]. However in this context, prevalance of culturally sanctioned polygyny [see @murdock1967], has been interpreted as evidence for the general validity of Bateman-derived sex roles in humans, as polgyny seems to be testament to male promiscuity and directly lead to higher variance of male reproductive success (Bateman's second principle) by unequally distributes mating opportunities among men [@schmitt2005]. Multiple researchers have cautioned against the use of this unsophisticated analogy [@brown2009; @borgerhoffmulder2009; @smiler2011]. For one, @murdock1967 's ethnographic data, often the primary citation regarding the cross-cultural prevalence of polygyny, itself shows that while polygynous marriage is often allowed, it is comparatively rare - that is to say, even in polygynous societies many males are monogamous. Conversely, both monogamous and polygynous societies may be marked by "serial monogamy" (i.e. remarriage or re-partnering), which further disolves the relationship between marriage systems and actual mating patterns [@fortunato2018], and leads to the emergence of female mating behaviour favouring multiple partners [@borgerhoffmulder2009]. It is unclear whether the coy female-ardent male dichotomy clearly derives from these patterns [@brown2009].These difficulties are also exacerbated by the fact that "promiscuity" is a somewhat ill-defined concept that can either refer for the number of partners (mate-number promiscuity) or the number of matings [mating-number promiscuity; see @ShusterStephenM.2003Msas]. The operating definition is clearly relevant in the context of mating and marriage systems as only mate-number promiscuity is necessarily indicative of polygamous mating.

It is worth noting that these critiques ought not to be interpreted as entirely invalidating Bateman's contributions or his eponymous principles per se [see @morimoto2020], and that it would be counterproductive to simply dismiss an entire body of well-evidenced associated research [@wade2005; @janicke2016]. But they do draw attention to the fact that, in their applications to humans in particular, Bateman's principles have both been fuelled by, and have fuelled, out-dated preconception about traditional sex roles and behaviours [@knight2002] - that is to say, normative *a priori* assumptions about how females and males *ought to* behave. Arguably, such imposition of social stereotypes on biological principles and vice versa impedes epistomological efforts in both science and society, which neither are likely to benefit from. Instead, a research approach based on the careful re-examination of the Darwin-Bateman paradigm allows to amplify and extend our understanding of the evolution of sex roles and mating strategies in a way that an over-reliance on Trivers' arguments would simply not allow for. Part of the purpose of this dissertation is to use recent theoretical advances in sexual selection theory to refine our understanding of the evolution of human mating and marriage systems. One key factor identified in the operation of sexual selection is the sex-ratio - which I shall now turn to.

## 1.2. Sex-ratio theory: principles and applications

**Basic tenets of sex ratio theory.** The causes, consequences, and evolution of sex-ratio patterns across biological species has been a point of contention throughout the history evolutionary thought. @darwin1981 himself wrote, after unsuccessfully grappling with it, that "the whole problem is so intricate it is safer to leave its solution for the future" (find exact page). Only over half a century later, after seminal works by @dusing1884 and @fisher1930, did biological science follow suit in formulating such a solution. Most notable in this context remains Fisher's key mathematical treatment of the topic, eponymously named Fisher's principle (or the Fisher condition), which explains why, evolutionarily, the sex-ratio at birth (SRB) converges toward an even 1:1 split. It is worth noting at this point that the Fisher's theory of sex-ratio and sex allocation is a null-model [that is to say, it makes a number of assumptions that many species may be expected to deviate from; see @west2009]. Nevertheless Fisher's explanation makes a simple and elegant observation: In sexually reproducing species, offspring generally have one father and one mother -- the overall reproductive success of the male and female population within those species is, therefore, equal. If one sex is rarer (that is to say, if the sex ratio is uneven), their average (or per capita) reproductive success increases relative to the more frequent sex. Their higher average reproductive success makes them, evolutionarily, more attractive and effective offspring. Consequently, parental genes which lead to overproduction of the rarer sex are likely to start contributing more to the gene pool as their offspring will have higher average reproductive success -- until, that is, they aren't the rarer sex anymore (and therefore lose their reproductive advantage). The equilibrium in which neither sex has a higher average reproductive success is a ratio of 1:1. That equilibrium is the Fisher condition. This does not run contrary to Bateman's principles, as these are concerned with sex differences in *variance*, rather than average reproductive success.

**Types of sex ratios and theoretical implications.** Fisher's theory is a useful starting point for examining and understanding sex ratios, but it comes with a number of corollaries. First off, it usually specifically refers to the sex ratio at birth (SRB), elsewhere referred to as the secondary sex ratio [@graffelman2000; but see @fromhage2016]. But the ratio of males to females tends to vary throughout an organisms lifecycle, and meaningful differences in the sex ratio is often seen at conception (SRC), at birth and in adulthood [ASR; also primary, secondary, and tertiary sex ratio, respectively, after @szekely2014]. Additionally, some researchers have advocated for the use of an intermediate "sex ratio at (sexual) maturation" (MSR), a concept closely related to, but temporally preceding, the ASR [@fromhage2016]. This is because, unlike the ASR, the MSR is not subject to bias resulting from, for example, sex-specific adult mortality or lifespan differentials [and thus allows for more straightforward application of the Fisher condition; see @jennions2017a]. Finally, while measures like the MSR and ASR count all living individuals at a given point in time, they might be misleading when it comes to mating markets because not all adults are going to be mate-searching at any given point in time. Instead, there is an operational sex ratio (OSR) which only includes sexually receptive individuals and dynamically responds to individuals entering and leaving the mating market (e.g. to care for their offspring, to enter monogamous pair bonds, etc.) - as such, it tends to oscillate over time [@delguidice2012]. In a continuation of the sexual selection work detailed above, the OSR was identified shortly after Trivers as an additional determinant of sex role divergence, with the argument that whichever sex the OSR is biased toward would experience higher intrasexual competition for mates and, by extension, stronger sexual selection, which leads to even more competition via a positive feedback loop [@emlen1977a; @kvarnemo1996]. @emlen1977a in particular related the OSR directly to mate monopolisability, arguing that, for example, a male-biased OSR is an indication of *male* ability to monopolise mates (e.g. through polygyny). This line of thought also suggests that a biased male-biased sex ratio leads to less investment in parental care and weaker pair bonds, as males invest in mate competition instead [@schacht2017c]. The empirical record offers no clear endorsement of such a relationship [@ims1988; @weir2011], and theoreticians have moved away from the OSR as a strong predictor of sexual selection and mate monopolisation [@klug2010; @shuster2009]. After all, there does not seem to be a strong *a priori* reason to believe that adding more members of the mate-limited sex offers more opportunity for mate monopolisation - if anything, it appears as if it would be harder to defend mates in that case. Indeed in humans, the OSR (though generally more broadly referred to as "sex ratio") is thought to be a key factor in the formation of "mating markets", in which the rarer sex gains quasi-economic bargaining powers in the formation of romantic relationships [@becker1981; @chiappori2020]. However, sociologists, psychologists and economists working within this space still commonly presuppose inherent sex differences in mating preferences [e.g. @regnerus2012], rather than letting them develop endogenously within their models - the very thing that theoretical biologists have cautioned against. I will discuss the current discourse on sex ratio theory in humans in greater detail below. In any case, given these conceptual difficulties, and the fact that measuring the OSR itself is problematic [@clutton-brock2017a], any work that aims to understand the evolution of mating system must look beyond biased OSRs alone to explain variation in mating behaviours [see @kokko2001; @kokko2003].

Instead of the OSR alone, recent work has highlighted the role of the ASR in determining reproductive strategies [@schacht2017b; @kappeler2017]. This is sometimes due to methodological necessity - in studies of human populations, variants of the ASR (like the ratio of marriage-age males to females) are often used as stand-ins as the true OSR is difficuly to determine [@wehbe2020]. More generally, the ASR and OSR are of course closely related - a biased ASR may well lead to a biased OSR, especially at the start of a given mating period [@jennions2017b]. But notably, ASR and OSR often display starkly different temporal patterns in wild populations, where the OSR tends to fluctuate more strongly due to fast-moving mating markets [@10.1093/beheco/arw183]. The ASR, on the other hand, is also directly determined by comparatively slower-changing demographic factors that only indirectly affect the OSR, like sex- or activity-specific mortality costs, and there are scenarios in which a sex might be in the majority in one but in the minority in the other [@kokko2008]. Interestingly, the OSR is simultaneously cause *and* consequence of mating systems, whereas the ASR is largely an external cause (unless reproductive decisions alter mortality risk - in any case, the strong impact of demographic processes on ASR is bound to weaken that reverse causality). Exploring this causal role of ASR in mating system formation, recent theoretical biology work has reversed or at least revised some of Emlen and Orings's early predictions regarding the effects of a sex ratio imbalance - rather than increasing the competition for mates in the more abundant sex, a biased sex ratio (either OSR or ASR) may actually reduce the benefit derived from competing for mates relative to guarding existing mates or caring for one's offspring. In short, if the cost of competing is high, individuals should switch to cheaper ways of increasing one's fitness and forego competition [@kokko2008; @fromhage2008]. These models have found support from empirical and theoretical work which highlights that male-biased ASRs can indeed be predictive of higher male parental care and monogamy, or even polyandry, across species [@fromhage2005; @liker2013], or even within species via phenotypic plasticity [@karlsson2010]. For example, experimental studies of honey locust beetles have shown that ASR biases can even lead to the reversal of sex roles within species, lending further credence to the idea that sustained sex ratio differentials may influence the evolution of sex roles [@fritzsche2016]. But where might such ASR variation stem from? In fact, the ASR is determined by a variety of demographic and ecological factors, which have been investigated in a wide range of evolutionary models [@szekely2014]. Importantly, as a result of this causal mosaic, the ASR can vary substantially throughout the animal kingdom - tendentially, for instance, birds have male-biased and mammals female-biased ASRs [@donald2007]. Nevertheless, the origins of such biases remain largely obscured, though recent work in avian species argues for a significant influence of juvenile mortality in the formation of ASRs [@eberhart-phillips2017; @eberhart-phillips2018a]. Additionally, imbalances in the ASR of any given population can of course theoretically stem from deviations in any preceding sex ratio (e.g. primary or secondary), as well sex-biased dispersal or migration patterns and adult mortality or life-span differences [@veran2009; @kappeler2017a]. Much of this comparative work on the causes and consequences of adult sex ratios has been conducted in avian populations, partially because the social organisation of many mammalian species complicates the measure of biologically relevant ASRs [@kappeler2017a]. Within the social sciences, however, there has long been a burgeoning investigation of sex ratios in humans.

**ASR causes and consequences in primates.** TBD - as there is a fair amount of comparative work, I thought it might be good to survey some literature on sex ratio theory in non-human primates. I feel like it's a good idea to bring this kind of stuff into an evolutionary anthropology dissertation.

**ASR causes and consequences in humans.** Overall, and across many geographies, the sex ratio at birth (SRB) is somewhere around 105 or 106 males to 100 females, sometimes referred to as the "natural" (according to the WHO) or "expected" sex ratio [@owidgenderratio]. However, this ratio goes down to parity for sexually mature age ranges, and finally reverses in post-reproductive populations due to higher male adult mortality [@wisser2014]. Despite this general pattern of sex ratios in contemporary human societies often being relatively even, they vary remarkably across geographies, history and the human lifespan [@hollingshaus2019]. To begin to understand this, we can employ, in the first instance, the same set of tools that behavioural ecologists use to investigate causal patterns of ASR variation across species - namely the SRB, sex-specific mortality rates (both juvenile and adult) and sex-specific migratory patterns [@szekely2014]. In a comprehensive review, @orzack2015 showed that while the human sex ratio at conception is even, slightly higher female than male fetal mortality leads to the male-biased SRB detailed above. However, evidence suggests that the SRB can be influenced by environmental factors spanning from the physiological, e.g. hormone-induced male fetal loss [see @james2017a], to cultural practices such as sex-selective abortions [@zhou2012; @qayyum2017], which induce geographical variation to SRB patterns. Similarly, sex-specific child mortality rates vary cross-culturally [@kishor1993], further exacerbating such variation, with some researchers asserting that this variation is systematically predicted by cultural gender equality norms and associated practices such as female infanticide [@bhatnagar2012; @iqbal2018]. Adult sex-specific mortality, too, often studied by demographers through what is called the "gender mortality gap", also showcases significant cross-cultural variation predicted, in part, by differences in health behaviours and their respective cultural relevance [@rochelle2015]. Sex differences in adult mortality may also be brought about by warfare and other forms of intergroup-conflict which disproportionately affect and involve men [@ember1974]. Finally, evidence for evolutionarily ancient sex-specific human migratory patterns has been revealed by genomics and genetics research [@seielstad1998; @perez-lezaun1999; @hammer2008], mirroring contemporary sex-specific trends for example in labour migration which may reflect local economic circumstances [@sharpe2001]. It stands to reason that the ways in which these factors interacts with cultural practices, as demonstrated in some of these cases, may give rise to significant consistent geographical variation in ASR patterns. Likewise, if the ASR is itself causally related to the evolution of certain cultural practices like marriage norms, this could indicate an interesting reciprocal relationship between demography and culture.

In any case, establishing that adult sex ratio imbalance and variation exists is of course only the first step - its impact has similarly been the source of much scientific inquiry. Notably, outside of the domain of biologists, the adult sex ratio in humans has been of interest to social scientist for a long time. In his early formulation of marriage market economics, @becker1973 reasoned that sex ratio imbalances influences the bargaining powers of either sex in the marriage market and determines how the "output" of a marriage is divided between the partners, with the rarer sex commanding a larger share and better chances in the marriage market. He also argues that an imbalanced sex ratio is one of the few circumstances that could lead to polygamous marriage, as he sees monogamous unions as more economically efficient [but see @gould2008 for a review of the precise circumstances under which monogamy may not be economically efficient]. In general, Becker's approach has proven enduring even in more contemporary economic models of marriage (many of which treat marriage as a "matching problem" for two sets of broadly complemtary types of people, men and women), and has even found support in empirical economic analyses [@angrist2002; @chiappori2020]. Adjacently, sociologists @guttentag1983 wrote broadly on the effects an imbalanced sex ratio, examining predominantly how variations in the adult sex ratio have affected the perceived value of women. Though stemming from a different methodological tradition than Becker, their conclusions read similar: The rarer sex enjoys relatively more "dyadic" power, which is expressed in male promiscuity in the case of a female-biased sex ratio, and increased male devotion to family in male-biased populations. Sociology continues to employ sex ratio as a demographic factor influencing gender (in)equality in the spirit of this work, sometimes referred to as "social exchange theory" [@stone2019]. Crucially, however, traditional sex roles and structural differences between male and female power are not endogenous to this approach - conversely, this theory specifically presupposes patriarchal power structures which interact, but do not arise from, sex ratio patterns. Finally, anthropologists, keenly aware of the diversity of marriage practices, have argued that sex ratio imbalances may cause the adoption of certain marriage norms like polygyny. Interestingly, the roots of this work precede almost the entire scientific discourse around sex ratios [cite Spencer here]. Early empirical work indicated that in a random sample drawn from the Ethnographic Atlas, polygynous societies did indeed show a more female-biased sex ratio (associated here with high male mortality from warfare; @ember1974). More recently, a female-biased ASR was found to be associated with lower male investment in mating effort among the Makushi of southern Guyana [@schacht2015], and a male-biased ASR was predictive of a lower variance of mating success among women in Northern Ireland [@uggla2017], both results in line with prediction from recent parental investment theory. Indeed overall, early results from economics, sociology and anthropology seem to largely reflect a common theme despite their starkly different methodological traditions. It is, however, worth reviewing how exactly adult sex ratio has been found to be associated with differences in human mating and marriage practices in more recent empirical work.

After the largely theoretical "social exchange" accounts by Guttentag, Secord and Becker, many social scientists have put their general predictions concerning the influence on sex ratio on varying mating and marriage practices to the empirical test, and especially whether sex ratio predicts the strength of pair bonding across societies. For example, a common prediction of this approach is that more male-biased sex ratios (hereafter "higher sex ratios", as sex ratios are often expressed as the number of males to females) will predict higher marriage rates, as it disincentives short-term mating in males [see also @schacht2015]. As such, marriage rates are commonly interpreted as individuals foregoing quasi-polygamous arrangements in favour of monogamous mating and the chance to secure a mate *at all* (meaning that associated studies are generally restricted to populations with monogamous marriage norms). Accordingly, empirical analysis has shown that, across a broad set of samples including historical populations in the US, Canada, and Russia, as well as cross-cultural data, the marriage rate tends to be higher in more male-biased populations [@angrist2002; @brainerd2017; @goldman1984; @south1988; @trovato1988]. There are a number of caveats to this, however. For one, in some special populations with unusually high sex ratios, namely India and China, where the SRBs may approach 120 males to 100 females, this pattern can be reversed in males through what demographers call a "marriage squeeze" on excess males, which technically actually lowers the male marriage rate as many men are failing to secure marriages rather actively avoiding them [e.g. @guilmoto2011; @jiang2014]. Such marriage squeezes can of course affect both sexes, depending on the sex ratio [@jones2006]. Additionally, it is worth noting, as suggested above, that many of these studies suffer from largely being focused on large-scale monogamous societies when using marriage rates as a proxy for pair-bonding.

In an interesting and valuable parallel, some anthropological work on small-scale societies has instead focused on "divorce rates" as an empirical proxy for strength of pair-bonds. Notably, @blurtonjones2000 found that in a hunter-gatherer sample including Hadza, !Kung, Ache and Hiwi populations, a lower sex-ratio is associated with higher divorce rates, and thus weaker pair bonds. Furthermore, empirical analysis of divorce rates has of course not been restricted to foraging societies. For example, large scale cross-cultural analysis using data from the late 20th century associate high sex ratios with lower divorce rates [@south1988; @trent1989]. However, the effects here are less one-dimensional as it may appear. In one notable study of divorce rates across US cities, @south1995 found that divorce rates actually increase when sex-ratios deviate *either way* from the overall population mean - meaning that pair bonds appear to weaken both in the presence of a relative male-bias and a relative female-bias. The authors relate this to Becker's theory of relative bargaining power, but it also reflects predictions from contemporary biological theory, namely that both male and female mating behaviour may actually be affected by sex ratio swings in a similar manner, rather than being necessarily differentiated by inherent sex differences. As with the marriage squeeze, the possibility of symmetrical effects of sex ratio is an important consideration for the research at hand.

Finally, there is some evidence that even in humans , sex ratios may impact the dynamics of sexual selection by influencing mate choice. The logic of this hearkens back to @emlen1977a 's work - the rarer sex can afford to be "choosier" and thus steers sexual selection - but is also reflected in the more social-scientific mating market approaches. A lot of the empirical literature on this effect of sex ratio biases has focused on the ability of women to choose wealthier and more educated men in male-biased populations [@albrecht1997; @pollet2008]. This may reflect an opportunity for women to select better "male provisioning" by choosing partners with high earning potential. However, no empirical research has been conducted on the reverse - whether low sex ratios lead to higher male choice (and marriage) of provisioning females. This is likely at least in part because much of the work on the issue has been conducted on historical populations where female educational and earning potentials were significantly constrained. An alternative proxy through which to consider mate choice are mate preferences, prominently explored in evolutionary psychology [@buss1989]. This evidence must be considered carefully, not least because mate preference may not actually mirror mate choice particularly closely [@todd2007], but it may offer some interesting insights into the effects of sex ratio. Notably and somewhat confoundingly, a study on the issue revealed that while male preferences seem largely unaffected by sex ratio, female preferences for provisioning proxies like "good financial prospects" and pair-bonding proxies like "mutual attraction - love" are actually negatively correlated with sex ratio, i.e. these preferences matter less to women in high sex ratio societies [@stone2007]. However, the same study did suggest that female preference for "chastity" was positively correlated to sex ratio, meaning that women seemed to put increasing emphasis on monogamous mating in high sex ratio environments - though far from definitive, this finding reveals a mechanism by which monogamous mating may be sexually selected for.

The preceding paragraphs are primarily concerned with the influence of sex ratio on inter-sexual behaviours, but, as discussed, sexual selection also operates through intra-sexual competition. A common prediction in this context is that intrasexual competition in males in particular takes the form of violent behaviours [@daly2001]. Consequently, sex ratio imbalances, and particularly male bias, are sometimes viewed as catalyst for violent behaviours [@hudson2002], ostensibly because males are forced to compete aggressively over restricted mating opportunities [@hesketh2006]. On the population level, this should translate to an association between sex ratio and, for example violent crime [e.g. @messner1991]. This prediction of "bachelor-driven" violence of social instability runs counter to the evidence indicating that higher sex ratios are actually predictive of more stable pair-bonds discussed above. Indeed, researchers have suggested that thinking about violence as an effective form of intrasexual competition in this way underestimates the influence of female choice, as well as misinterprets what male intra-sexual competition actually looks like - after all, there appears to be no strong reason to believe that men would compete violently rather than, say, on parental care or provisioning ability [@schacht2014]. Overall, this is in line with the mating market approach which would predict that male mating effort should increase when males are abundant, leaving relatively little room for high-cost intrasexual competition in the form of violent crime. Empirical evidence on the issue is decidedly mixed, with some studies repeatedly pointing toward the fact that higher sex ratios are actually associated with reduced crime violent crime and homicide rates [@antonaccio2007; @barber2000; @schacht2016c], whereas others find the positive association predicted by more traditional approaches [@diamond-smith2018; @edlund2013; @vandello2007]. @Filser2021 hypothesise that these mixed results are likely due to methodological complications (e.g. level of analysis), unobserved regional heterogeneity and further imprecise use of aggregate data irrespective of sex of either perpetrator or victim, and instead suggest that the debate requires more precise analysis of individual-level data (e.g. specifically investigating patters of violence against women, or violence perpetrated by childless men) which may in turn lend themselves to more nuanced hypothesis. For example, there is data to suggest that intimate partner violence actually increases in male-biased populations, which, decidedly crudely, could be interpreted as a form of mate-guarding [@bose2013; @diamond-smith2018; @dalessio2010]. Overall, the relationship between sex ratio and violence is only tangentially related to the study at hand, but it serves as a useful reminder that any approach that means to understand the relationship between sex ratio and behavioural patterns would do well to approach aggregate data carefully.

**Computational modelling.** This empirical literature on the effects of sex ratio has been complemented by (sometimes specifically human-focused) mathematical modelling approaches that integrate some intuitions generated by the empirical results discussed here with the broader novel theoretical approaches detailed above [e.g. @kokko2008]. Nevertheless, explicit modelling of sex ratio and the evolution of different mating strategies in humans remains relatively rare, with an number of notable exceptions. @schacht2016a investigate how partner scarcity affects male mating strategies using an individual-based recursive model, finding that a male-biased sex ratio shifts the optimal strategy towards mate guarding of existing partners, thus favouring the evolution of monogamy within those systems. @loo2017 replicate and extend these finding using an ordinary differential equation (ODE) model, reaching similar conclusions. @coxworth2015 use agent-based modelling (ABM) to show that adult sex ratios relevant to reproduction are often male-biased due to the human life history, where women enter the post-reproductive stage earlier than men and thus "leave" the reproductive pool, and argue that this may account for the evolution of strong pair-bonding via mate guarding. Making a similar link between the evolution of monogamy, sex ratio variation and mate guarding, @gomes2018 construct an agent-based model in which male-biased populations tend towards monogamy, but only if efficient mate guarding is possible. Overall, these modelling approaches mirror the general learnings from the empirical literature - namely, that ASR does seem to represent a causal factor in the formation of mating strategies overall, and more specifically, that it favours the adoption of monogamous over promiscuous strategies, especially in male-biased populations. But they often make simplifying assumption regarding the way in which mating strategies propagate, often simply assuming they are purely genetically inherited [e.g. @gomes2018]. This may belie a more complex reality, especially when it comes to humans, where genetic and cultural inheritance, both of which are likely to play a significant role in the formation of mating strategies, interact in complex ways [@richerson2005, see also Section X.]. Modelling approaches to human mating which do take this co-evolutionary dynamic into account tend to focus on the evolution of particular aspects of mating strategies, like incest avoidance [@aoki1997] or partible paternity beliefs [@mesoudi2007], rather than the evolution of monogamous behaviour more general. Sometimes these models do include sex ratios as an explanatory parameter - for example, @mesoudi2007 's results suggest that within their agent-based model, biased sex-ratio imbalances in either direction favour the evolution of monogamy. In other cases, they explicitly endogenise sex ratio as the factor that is co-evolving (e.g. with sex-selective cultural practices) in their simulations, rather than treating it as parameter [@kumm1994]. In any case, none of them allow for mating strategies to be co-determined by evolved genetic and cultural factors. But should they? Arguably, human mating may evolve biologically, as is assumed in the majority of the mating system models discussed above. On the other hand, human mating is subject to complex systems of norms and cultural beliefs which determine the type of mating behaviour that is permissible - and such cultural practices like follow a separate inheritance system. In other words, an examination of human mating is likely rendered incomplete lest it considers the evolution of human marriage systems.

## 1.3. Explanations for marriage patterns in humans

TBD. Briefly review some common theories put forward to explain the evolution of monogamy as a cultural practice. This breakdown largely reflects Minocher et al. (2019)'s recent paper on the matter, which I found to be a fairly useful starting point.

At first glance, it may seem tempting to extend the vast biological literature on mating systems across species to the evolution of human pair-bonding. In fact, much of the discussed work does just that, if often cautiously. Importantly, however, this caution is certainly warranted as a straightforward application has largely eluded scientific consensus for a number of reasons. But before delving into this, it is useful to make some broad definitions. Broadly speaking, "mating system" refers to the, generally species-typical, way in which a species' sexual and reproductive behaviour is structured, primarily in reference to the number of sexual partners an individual entertains within a certain time period [@kokko2014]. They generally take one of two forms - monogamy, which is a one-to-one pairing, or polygamy, which may include multiple partners of either sex. More precisely, "polygamy" includes polygyny (one male with multiple female partners), polyandry (one female with multiple male partners) or polygynandry [or polyandrogyny, clusters of multiple male and female partners; @shuster2003]. Confoundingly, these descriptions can be applied either to single mating cycles or an individual's lifetime - as such, some species may be seasonally monogamous, but polygamous across the long run [e.g. @moore2009]. Additionally, biologists now commonly distinguish between genetic mating systems and social mating systems [@gowaty1996]. Social mating systems refers primarily to the pair-bonding and parental care arrangements of a given species, while the genetic mating system accounts for often divergent patterns of paternity and fertilisation - for example, due to extra-pair copulations, even socially monogamous, pair-bonding species may be genetically polygamous [@pechacek2005; @wiebe2009].

Even within this framework, the human mating system is challenging to pin down still. For one, it is difficult to define a "species-typical" mating arrangement for humans in the first place. While the mating behaviour of most vertebrate species can reasonably be uniformly characterised through a single system (differences between genetic and social mating systems notwithstanding), human mating arrangements show considerable diversity [@low2007]. For example, in their landmark classification of 186 distinct human cultures from the ethnographic record in the Standard Cross-Cultural Sample (SCCS), @murdock1969 code 17% of recorded societies as monogamous, with the other 83% sanctioning some type of polygamy (predominantly polygyny). Conversely, however, because many of these polygamous societies represent small-scale, pre-industrial societies, in absolute numbers, a majority of humans live in societies that are institutionally monogamous - further complicating any attempt to derive any human-typical mating pattern [@brown2009]. Secondly, even this argument assumes in the first instance a close correspondence between human mating systems and human marriage systems, but this has recently been questioned by evolutionary anthropologists [@fortunato2018]. Mating systems are, fundamentally, patterns of behaviour - they are descriptive rather than normative. Marriage systems, on the other hand, are almost by definition normative; they are sets of rules that legitimise, govern and often restrict, rather than merely describe, sexual and reproductive behaviour in humans, including ancillary behaviours such as parental obligations and inheritance [@fortunato2015]. As such, marriage systems are only an accurate representation of mating systems as far as these rules are strictly adhered to and there is no extra-marital reproductive behaviour - an unrealistic assumptions for a wide range of human societies [@blow2005; @walker2010]. This somewhat mirrors the difference between social and genetic monogamy described earlier. Additionally, some marriage systems only sanction normative behaviour at a given point in time, rather than across an individuals lifespan. As such, even in monogamous societies, divorce and remarriage may lead to overall mating patterns that are effectively polygamous, or "serially monogamous" [@borgerhoffmulder2009].

The matter is further complicated by the fact that a marriage *system*, by virtue of being normative rather than descriptive, may not even necessarily reflect the marriage *patterns* observable in a given population or culture. For example, even though polygamy is widely sanctioned, it is not enforced, and in reality often only rarely practised - while 83% of societies in the SCCS are polygynous, in only 28% is polygynous marriage actually practised in more than 40% of recorded marriages [@murdock1967; @marlowe2003]. Finally, even "mating patterns" as defined by the actual, observable pattern of sexual interaction within and outwith marital arrangements is detached from the genetic level of mating systems, for example through the use of contraceptives [@oreilly2010]. In summary, the disconnect between human marriage systems and human mating systems is therefore three-fold - marriage systems may not necessarily represent actual marriage arrangements, marriage arrangements may fail to adequately capture all sexual interactions, and finally sexual interactions may not actually reflect reproductive activities. Nevertheless, evolutionary sciences still often employ this somewhat crude heuristic and habitually treat marriage systems as indicative of underlying alternative reproductive strategies [e.g. @buss1993].

These conceptual and methodological challenges notwithstanding, the evolution of human marriage and mating systems continues to draw extensive scientific interest [@schacht2009a]. Particularly, in light of the relative rarity of monogamy among mammals [cite here] and even many human societies [@murdock1969], researchers often speak of monogamy as a fundamentally counter-intuitive mating pattern, labelling it a "paradox", "mystery" or "puzzle" across human and non-human mammals alike [@carter2018; @henrich2012; @gould2008]. Implicitly, this appears to be rooted in the idea that monogamy represents a deviation from the baseline mating pattern, which is polygamy, or polygyny in particular [@low2007]. Accordingly, though others have argued that human life history constraints, especially the extended dependence of offspring on parental care, may fundamentally favour monogamy [@lancaster1987; @kaplan2000; but see @hrdy2009], most approaches have focused on determining under what circumstances monogamy may arise from polygamous arrangements [@chapais2013; reviewed in @fortunato2015 and @minocher2019a]. In fact, both comparative evidence from the mating systems of extant non-human primates and phylogenetic analyses suggests that *some form* of polygamy likely represents the ancestral mating system for the genus Homo [@opie2012; @chapais2011], though it is worth noting that mating systems in great apes vary substantially both within and between groups, including both harem-defense type polygyny in gorillas as well as promiscuous polygynandry in chimpanzees and bonobos, somewhat obscuring their evolutionary history and perhaps limiting the efficacy of primate models in this context [@grueter2012; @nakahashi2012]. Regardless, even constricting the time horizon to more recent evolutionary history (i.e. the last 100k years), it has been suggested that the last common ancestor of all extant human populations had at least moderate levels of polygamy [@minocher2019a]. There are number of important caveats to these findings. For one, they also suggest that the evolution of marriage systems is *not* a unidirectional transition from polygamy to monogamy - some extant population may exhibit stronger polygamous tendencies than ancestral populations and vice versa. Similarly, this is not to say that monogamy necessarily co-emerges with features of "modern" or "complex" societies, as has been suggested elsewhere [e.g. @blumberg1972; @levinson1980; @enke2018], as monogamy in Eurasia, for example, appears to precede these features substantially [@fortunato2011; @fortunato2020]. It is also worth noting that this "polygyny baseline" idea is effectively a direct derivation of the Darwin-Bateman paradigm of ardent males and coy females, underscored by the same sexual selection theory literature that is undergoing revision, and has been subject to similar criticisms, often principally relying on sexual conflict [@fortunato2015]. That being said, the shortcomings of this approach have been discussed at length elsewhere in this review.

Overall, it appears likely that there have indeed been bidirectional evolutionary transitions between different marriage patterns across certain cultures and geographies - but what factors influence these changes remains a topic of debate. A full review would far exceed the scope of this introduction (but see @fortunato2015), so I will only briefly recount the most common theoretical frameworks, honing in on the one that is most relevant to the dissertation at hand. In a comprehensive recent review, @minocher2019a categorise contemporary hypotheses into 5 distinct theoretical models: the polygyny threshold model (model 1), inheritance of rival wealth induced monogamy (model 2), harem defense or mate guarding polygyny (model 3), cultural group selection monogamy (model 4) and market forces polygyny (model 5). The polygyny threshold model draws heavily from extended behavioural ecology in predicting that polygyny may be the result of female mate choice of wealthier males in environments where resources are distributed unequally [@orians1969; @verner1966]. The underlying idea is that there may be a high enough net resource benefit to women being polygynously married to wealthy partners (i.e. becoming additional wives), when the monogamous alternatives are comparatively resource-poor [@borgerhoffmulder1990; @sellen2004]. "Resources" in this context can be broadly defined and extended beyond material or physical wealth to include social capital or even genetic qualities that protect offspring against prevalent diseases [@chaudhary2015; @low1990]. However, recent empirical analysis suggests that physical resource inequality is actually predictive of macro-level trends towards monogamy rather than polygyny, refuting the central prediction of this model [@scheidel2009; @ross2018]. This ties into an alternative explanation, which instead emphasises the role of inheritance of rival wealth - resources that have to be divided among offspring [@oh2017]. Where such partitioning of wealth leads to reduced fitness for the inheritors, evolution may favour monogamous arrangements which effectively funnels resources from one generation to the next instead of dividing between potential heirs from multiple wives [@fortunato2010]. Forms of such rival wealth, like land, become more important in agricultural production systems, which are in turn often marked by higher levels of inequality (when compared to, for example, horticulturalist systems), thus offering an explanation for the association between higher inequality and monogamy [@ross2018; @mattison2016].

Where polygyny threshold models primarily invoke the role of female choice (in the broadest sense), harem defense or mate guarding approaches to polygyny tend to instead emphasise the role of male coercion and non-resource based male-male-competition in enforcing polygynous marriage systems [@chisholm1991; @marlowe2000]. Accordingly, some evidence suggests that polygyny is associated with heightened level of male intrasexual violence [@carter2018b] and partner-directed violence [@ahinkorah2021; @ebrahim2020; @jansen2020], with the latter posited to represent a direct form of physical coercion. However, it is important to note that intimate partner violence in humans can and should not be unduly reduced to a mate guarding strategy [e.g. @wilson2009], and that the link between polygyny and increased level of intrasexual violence in men are not consistent [@schacht2014]. Using similar evidence of links between violence and polygyny, one influential account invokes the role of monogamy in limiting intragroup conflict for mates [@henrich2012]. Early versions of this argument posited that "socially imposed" monogamy served to preserve group cohesion, typically in democratic societies, by equalising reproductive capabilities [@alexander1979; @alexander1987]. More recently, however, this logic has been extended in the context of cultural group selection, where monogamy represents a group-level trait that allows cultural groups to redirect resources from intra-group mating competition to intragroup cooperation, which in turn allows for higher success in intergroup competition [@henrich2012; @richerson2016; @handley2020]. However, cultural group selection theory remains controversial [see commentaries on @richerson2016], and the central underlying mechanism - that monogamy is conducive to intragroup cooperation - remains empirically untested.

Finally, the market force polygyny approach employs the same "biological markets"-derived relationship between sex ratio and mating systems discussed in previous sections, and applies it more specifically to the formation of marriage systems [@noe1994; @minocher2019a]. As opposed to other theories which tend to emphasise either female choice (as in the polygyny threshold model) or male coercion (as in harem defense polygyny), this approach assumes that marriage system formation is subject to mutual choice of both sexes under the bargaining constraints afforded by the relevant sex ratio. For example, @pollet2009 show that prevalance of polygyny across localities in Uganda is associated with a female sex-ratio, and @ember1974 observe a similar pattern across cultures drawn from the Ethnographic Atlas. However intuitive, the market-driven approach to the evolution of polygyny is subject to both empirical and conceptual challenges. @quinlan2007 fail to find a meaningful relationship between sex ratio and polygyny in the Standard Cross-Cultural Sample, while @ember2007 find it only in non-state societies (reflecting cultural group selection ideas that larger institutions may inhibit biological markets). In an attempt to derive the evolutionary history of marriage systems while testing different theories, @minocher2019a find no evidence for an influence on sex ratio on marriage system formation across the SCCS while accounting for cultural relatedness, but they are limited to the sex ratio data recorded in the SCCS for this analysis, which only provides a snapshot of the sex ratio at a given moment. Generally, while these types of cross-sectional studies may reveal "still image" patterns of correspondence between sex ratio and marriage system (including evidence both for and against this theory), they only allow for limited inference about the dynamic evolutionary process that may link the two. The Fisher principle limits the potential for sex ratio imbalances to persists over long periods of time, but temporary shocks to the sex ratio, for example via war, disease or migration [e.g. @plumper2006], may yet influence marriage systems along the lines of biological markets theory. This is particularly plausible if even temporary imbalances can lead to the formation and cultural evolution of marriage specific social norms that may constrain behaviour for many generations via cultural inheritance [@richerson2005]. Indeed, there is some evidence that temporary historical sex ratio imbalances can have an long-term influence on certain cultural traits like attitudes towards gender roles [@grosjean2019]. Combining this cultural evolutionist intuition with the logic of the biological market theory of marriage may shed light on the ways in which sex ratio influences marriage systems beyond cross-cultural analysis.

## 1.4. Gene-culture coevolution

TBD. As the model is used to simulate a gene-culture coevolutionary process, it would probably be wise to sum up this methodological framework and explain how it can be applied to the evolution of mating / marriage systems. I think a potentially interesting interaction is that the modern biological approach to sex ratio, similarly to the Fisher principle, predicts a kind of negative frequency-dependent selection - the rarer phenotype enjoys comparatively more advantages / higher fitness. Conversely, cultural evolution is often thought to be affected by positive frequency-dependent selection (e.g. conformity bias). I think it is interesting to think about how those two forces may interact (though NB that the base model does obviously not model conformity bias).

I have at various points asserted that the evolution of marriage systems may be most effectively modelled as a gene-culture coevolutionary process, combining the evolution of human mating as a biological disposition with the evolution of cultural marriage norms. Gene-culture coevolution (or dual inheritance) theory posits that genes and cultures are two separate inheritance mechanisms which generate (potentially adaptive) phenotypic change across time [@aoki2001; @richerson2010a; @whitehead2019]. Crucially, this assumed that culture, broadly defined as socially transmitted (read: socially learned) information, and cultural change can be modelled using the tools and insights afforded by an Darwinian evolutionary framework, even if the mechanisms of this cultural evolution are not perfectly analogous to its biological counterpart [@mesoudi2011; @cavalli-sforza1981; @richerson2005]. A key prediction of gene-culture coevolution theory is that these processes not only run in parallel, but that they interact: On one hand, genetic propensities and biological predisposition (e.g. learning mechanisms) may shape the way cultural information is acquired and transmitted, but on the other, cultural practices may modify the selection pressures through which natural selection affects the human genome [@laland2017; @kendal2011]. But while such interactions have been repeatedly shown to be highly plausible in theoretical accounts [e.g. @gintis2003], empirical evidence remains comparatively scarce with a number of notable exceptions [@laland2010]. One such exception, and a useful illustration, is the coevolutionary process which is posited to have shaped human adult lactose tolerance and the associated ability to digest dairy. Most humans, like most mammals, lose the ability to digest lactose, a principle component of milk, as they mature [@scrimshaw1988], however, some populations retain this ability, termed lactase persistence for the corresponding lactose-processing enzyme, due to genetic variation in the lactase gene LCT [@swallow2003; @lewinsky2005]. Interestingly, those population also tend to have a strong cultural history of cattle farming and milk consumption, leading some the hypothesise that dairy farming, as a cultural practices that provided a novel source of milk in the diet, may have shifted selection pressures to favour lactase persistence [@gerbault2011; but see @segurel2017]. This represents an oft-cited textbook example of gene-culture coevolution. To assess now whether this approach offers a strong framework for understanding the evolution of marriage systems, two questions need to be answered: Do marriage systems rely on both genetic and cultural factors that can plausibily interact? And does the application of this approach have the chance to offer novel insights which a different framework would not provide?

The first questions can be answered affirmatively by making the relatively light assumption that human mating strategies and marriage systems are shaped by both genetic and cultural influences. Indeed, the role of genetic mating preference traits is routinely assumed in evolutionary models of human mating systems [@mesoudi2007; @gomes2018a] - a reasonable assumptions considering that genetic influences are likely part of what determines mating systems across taxa, including primates [@shuster2003]. Outside of this somewhat unsophisticated "common sense" argument, however, recent investigations into the genetics of human social behaviour have indicated that certain marriage and pair-bonding related preferences may indeed be genetically heritable [@trumbetta2007; @whisman2017]. For example, @walum2008 found that polymorphisms in the *AVPR1A* gene are associated with differences in pair-bonding behaviour in men. A growing body of literature indicates that genes regulating vasopressin and oxytocin pathways play a role in determining affiliative, including romantic, behaviour in both sexes [@feldman2016; @monin2019; @walum2012], reflecting convergent evidence on the neurological underpinnings of human attachment [@feldman2017]. Though most of this evidence stems from behavioural genetics studies, which should be treated with care [see @abdellaoui2021], overall there appears to be good evidence that genetic factors play a role in human romantic attachment. As this could have an impact on mating behaviour, for example fidelity, they may thus also for the basis for a biological disposition toward monogamy or polygamy. Perhaps less controversial is the idea that marriage systems are also determined by culturally transmitted traits. As noted above, marriage systems show considerable cultural variability, and the divergent cultural evolution of social institutions, which includes rule systems that regulate marriage and reproduction, is well conceptualised [@bowles2004; @boyd2008]. As a result, evolutionary anthropologists routinely treat marriage norms as socially transmitted cultural traits [@mace2005a; @lipatov2011]. Additionally, in accordance with cultural group selection accounts of marriage system evolution, it is possible to conceive beliefs concerning monogamy and polygamy fundamentally as cooperation-like norms, perhaps representing moral concern over "fair" mating arrangements [@henrich2012]. This interpretation allows for an interesting analogy to be drawn between our co-evolutionary approach to marriage systems, and the coevolutionary dynamics of cooperation, which similarly is posited to include both genetic (innate prosocial proclivities) and cultural (norms and rules regulating interactions) factors that scaffold each other [@boyd2009; @henrich2010; @lindenfors2017].

The second question, conversely, is harder to answer, but represents a key point for this dissertation. What does a co-evolutionary approach have to offer in terms of scientific novelty? First of all, cultural evolution differs from genetic evolution in ways that may have interesting implications for the evolution of marriage systems. While biological evolution relies fundamentally on vertical transmission of traits [i.e. from parent to offspring; @mayr1982], cultural traits need not necessarily be transmitted vertically. Instead, they can theoretically be acquired from any other individual, including peers (via horizontal transmission) and non-parental individuals from the parent generation [via oblique transmission; @cavalli-sforza1981]. In reference to marriage system evolution, this means that cultural mating preferences are not necessarily propagated via sexual reproduction, as is the case with genetic traits, but can be acquired from non-reproductive individuals who serve as "cultural parents" [e.g. @enquist2010], weakening the link between reproductive success and associated cultural mating preference (biological mating preference traits would still be tied to reproductive success). This is especially relevant because polygamy (over monogamy) is associated with higher reproductive success, particularly in men [@gibson2007], which would seemingly favour the propagation of polygamous traits in exclusively genetic inheritance scenarios. Similarly, cultural inheritance may not only be subject to different inheritance pathways, but also different modes of (cultural) selection which affect the frequency of socially acquired cultural traits within population, variably described as social learning strategies or transmission biases [@laland2004; @mesoudi2011]. One such transmission bias is conformist bias, which describes the tendency to preferentially acquire cultural traits held by the majority of the population [@denton2020]. Like non-vertical transmission, conformist bias also has interesting implication for the transmission of marriage preference. For example, the viability of polygamy is bound to depend both on the number of available partners (captured through the sex ratio) and the number of existing same-sex rivals, with rival "polygamists" posing a larger potential risk to reproductive success than rival "monogamists", as the former threaten to monopolise more mates. Indeed, evolutionary biologists often invoke this kind of negative frequency-dependence (certain mating strategies perform better if they are relative rare) to explain the maintenance of concurrent alternative reproductive strategies within taxa [@taborsky2010]. As a result, the frequency of mating strategies may oscillate around an evolutionarily stable equilibrium [@zamudio2000; @rios-cardenas2018]. We may expect to see a similar pattern in human mating strategies, but crucially, conformist bias introduces a unique element of positive frequency-dependence for cultural mating preferences. It is unclear how these counteracting forces would interact to shape marriage type frequencies over time.

As a final benefit, a gene-culture coevolutionary approach allows us to reflect the basic insight that marriage practices and mating strategies are conceptually distinct [cf. @fortunato2015], allowing for remarkable phenotypic variability across culture and biology, including mixed ones. Individuals may hold a moral belief about either monogamy or polygamy being the "right" marriage practice, but be biologically predisposed to another, offering an alternative explanation for phenomena like the relative rarity of polygyny even polygynous societies, or infidelity within strictly monogamous systems. This introduces a kind of continuous, or at least graded, variation between the extremes of polygamy and monogamy.

## 

1.5. Summary and hypothesis

TBD. A summary paragraph to tie all the open research questions into the research question at hand. I think upon redrafting, I'll have to add some clearer sign-posting throughout the intro, but this will be useful nonetheless.

# 2. Methods

## 2.1. Methodological approach

Over the course of the introduction and literature review, I have tried to emphasise the importance of using dynamic, rather than merely cross-sectional techniques in uncovering the evolutionary trajectory of behaviours such as mating and marriage. However, attempts to derive the intricacies of these dynamic processes from the empirical record, while undoubtedly important, are restricted by significant practical issues [@romanowska2021]. Indirect observation of past behaviours via artificts is restricted by data availability and preservation biases [e.g. @gallo2021], whereas backwards inference about past behaviours from present populations may, for example, be complicated by issues arising from equifinality of different behavioural patterns [@barrett2019]. In short, attempts at unravelling the evolutionary history of behaviours are generally a daunting undertaking. Due to these issues, and as a complement to empirical approaches, mathematical modelling techniques are now commonplace across many disciplines concerned with the dynamics of behaviour, including ethology, human psychology and of course cultural evolution [@goldstone2005; @henson2010; @cavalli-sforza1981]. Modelling allows researchers to formalise theoretical frameworks of varying sophistication, and then test their hypotheses and predictions *in silico*, via simulation or mathematical derivation. In an evolutionary context, this opens a direct window into a possible past, allowing us to investigate the roles and interactions of distinct causal mechanisms in the emergence of behavioural patterns [@romanowska2021].

The sophistication of these formal models often varies widely, but can be usefully conceptualised between two extremes. On the one hand, some mathematical models strive to reflect reality at closely as possible, by using realistic parameters and relational assumptions, to make testable, empirical predictions [e.g. meteorological or other predictive models; @anderson2003]. But conversely, there are also abstract theoretical model which explicitly intend to simplify vastly complex empirical phenomena down to a limited number of constituent parts. These "proof-of-concept" models primarily serve to translate verbal logical models into mathematical formulations, which can then be used to estimate and test corollary hypotheses [@servedio2014]. Although these types of "bare-bones" models are often viewed with skepticism by pure empiricists for their lack of nuance [e.g. @henson2010], they also epitomise the key advantage of formal modelling as a scientific technique - namely, the necessity of explicitly constructing the system of interest and all its parts, while laying out every assumption made in its design [@smaldino2017]. Unlike verbal models which open themselves up, intentionally or not, to ambiguity, formal models are as precise and tractable as they might appear simplistic - and in the process, offer a straight path from base assumptions to their logical conclusions [@gunawardena2014]. The present model represents one such "proof-of-concept" model. It is, by necessity, a crude representation of human mating and marriage systems, but it allows us to explicitly test the impact of our parameters assumptions on their evolution. So far as it adequately reflects existing evolutionary mechanisms, this may offer insight into their real-world evolutionary history. In any case, it will allow me to formally test some predictions derived verbally from the extensive literature on human mating and marriage reviewed above.

[ADAPT AGENT FIGURE FROM MACAL & NORTH]

Specifically, I will employ an agent-based model (ABM). Agent-based models simulate populations of discrete, autonomous individuals (agents) whose behaviour is stochastically determined by sets of individual attributes and predetermined decision rules [@bonabeau2002]. ABMs allow us to disaggregate population level phenomena, like patterns of marriage norms, by observing the emergent, bottom-up processes of agent-to-agent interaction through which they arise over time. This also represents their primary advantage over alternative population level modelling techniques, like differential equation modelling - agent-based simulations allow for considerable heterogeneity between agents with different attributes. Given that evolution relies on heterogeneity as a founding principle [cite that paper], this makes them particularly well-suited to the study of evolutionary processes [@deangelis2005]. The present approach represents a simplified "toy model" version of such an evolutionary agent-based model. By implementing basic processes including cultural inheritance and sexual reproduction, it aims to combine insights from models of both mating behaviour [e.g. dan conroy beam cite] and cultural evolution [cite the mesoudi textbook here], allowing me to observe the impact that changing some key parameters - namely the sex ratio - has on the evolutionary trajectory of mating and marriage system preferences. This serves as an example of the broader potential of this technique within the constraints of a "research proposal" style dissertation.

To take advantage of the considerable degree of transparency afforded by having to explicitly determine every element of a model, ABMs have to be examinable by a wide audience [@grimm2006]. Using natural language (in addition to appendix-bound formal representations) to describe the structure of the underlying formal models bears the risk of reintroducing ambiguity, but represents a useful compromise that makes ABMs tractable to a non-technical readership and reproducible for peers [@muller2014]. In light of these considerations, I will describe the present model using an extension of the common ODD (Overview, Design Concepts and Details) protocol proposed by @grimm2010 that specifically accounts for the nuances of describing models featuring simulated human agents, termed the ODD + D (plus Decision) protocol [@muller2013]. As the name suggests, the ODD model invites ABMs through three eponymous segments. I offer an abridged version of this protocol in this section - a full version can be found in Appendix X.

### 2.2 Model description

### 2.2.1. Overview

**Purpose.** The purpose of the model is to explore the role of individual-level genetic and cultural traits, as well as demographic constraints, in the evolution of human marriage systems. The model is primarily designed for natural and social scientists, specifically those interested in human evolution, with the aims of a.) testing hypotheses regarding the influence of sex ratio as a mating market constraint on the evolutionary process and b.) formulating a toy model which could be extended to examine the role of ancillary mechanisms, such as different social learning strategies.

**Entities, state variables, and scales.** The model simulates a population of 150 individuals (cite here), divided into four distinct types of human agents: female polygamists (FP), female monogamists (FM), male polygamists (MP) and male monogamists (MM). Each agent is characterised through four attributes, with two levels each: sex (male/female), cultural marriage preference (polygamy/monogamy), biological mating preference (polygamy/monogamy) and mating behaviour (polygamy/monogamy; see figure X). Mating behaviour determines mating strategy: Polygamists employ a "multiple matings" strategy, while monogamists employ a "single mating" strategy (detailed below). Each agent is capable of taking (a) reproductive partner(s) and producing offspring, the number of both of which is recorded in the model as state variables. There are also a number of exogenous variables in the model which serve as key parameters. Those include the starting population ratios of sex, cultural marriage preference and biological mating preference, as well as fixed parameters determining the continuous sex ratio of each new generation, and the maximum number of offspring per mating encounter for monogamists and polygamists, respectively. For this toy model, and to balance inferential demands with computational constraints, each simulation is run over 500 timesteps, representing non-overlapping generations of agents. Future iterations of the model could implement a longer time series allowing the model to always stabilise.

**Process overview and scheduling.** In each timestep, each generation goes through two sequential processes: mating and trait determination. At the start of each mating process, the population of individuals becomes the mating pool for that given generation. Individuals are randomly drawn from this mating pool to engage in mate search. If mates are available, they are then matched with a member of the opposite sex to simulate a mating encounter. Each mating encounter then proceeds to reproduction and results in a randomly determined, but constrained number of offspring, which are added to the next timestep's generation. Polygamists *only* will then mate search *again* for a second partner. Unlike the first mating encounter, the second encounter is not guaranteed, but derives its probability from the operational sex ratio - the rarer the opposite sex, the less likely a second mating encounter becomes. If a second encounter happens, it proceeds to reproduction like the first one. Monogamists are constrained to one mating encounter and partner, whereas polygamists can have up to two. Both monogamists and polygamists are removed from the matingpool as soon as these constraints are met. Mating and reproduction continues until number of offspring reaches the population constant of 150. This concludes the mating process. Next, each individual offsprings' traits are determined. Sex is stochastically determined based on the continuous sex ratio parameter. Cultural and biological traits are randomly inherited from one of the two parents via unbiased vertical transmission [cite here]. Finally, mating behaviour is stochastically determined based on the combination of biological and cultural traits [see Table X]. This concludes the trait determination process, and the simulation moves on to the next timestep.

### 2.2.2. Design concepts

**Theoretical and empirical background.** The model draws from multiple theoretical backgrounds, primarily sexual selection theory and cultural evolutionary theory, in the conceptualisation of its processes and parameters. Mating in the model follows the basic rules of biparental sexual reproduction [@lively2014]. Biological inheritance employs the rules of standard haploid inheritance [@mesoudi2007], whereas cultural inheritance happens through unbiases vertical transmission [the smolla book], derived from cultural evolutionary theory [@cavalli-sforza1981]. Note that these two processes, while conceptually distinct, are functionally identical and perfectly analogous in this model. For its parameters, the model employs approximations derived from empirical data and adjacent theory to simplify the model and limit the number of variables:

-   Polygamists are limited to two partners, in line with findings from contemporary polygamous societies in which the vast majority of polygamous unions do not exceed two opposite sex partners (Blurton-Jones 2016, Borgerhoff Mulder 2009, gibson & mace 2006, Timæus & Reynar 1998).

-   Monogamists can produce up to 5 offspring per matign encounter, whereas polygamists only produce up to 3 per encounter. This employs an approximation of Bateman's gradient in humans that predicts diminishing returns to mating success [@brown2009]. Recent empirical data seems to validate this

**Theoretical and empirical background.**

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| II.i.a Which general concepts, theories or hypotheses are underlying the model's design at the system level or at the level(s) of the submodel**(s) (apart from the decision model)?** What is the link to complexity and the purpose of the model? |                                                                                                                                                                                          |
+=====================================================================================================================================================================================================================================================+==========================================================================================================================================================================================+
| **II.i.b On what assumptions is/are the agents' decision model(s) based?**                                                                                                                                                                          | [**Established theories**]{.ul} **(micro-economic models: homo oeconomicus, full / bounded rationality; cognitive models: social psychology, mental models; space-theory based models)** |
|                                                                                                                                                                                                                                                     |                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                     | [**real-world observations**]{.ul} **(mechanistic explanations / process-based understanding available; black-box, use of heuristics, statistical regression methods)**                  |
|                                                                                                                                                                                                                                                     |                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                     | [**ad-hoc rules**]{.ul} **(dummy rules, e.g. constancy assumption)**                                                                                                                     |
|                                                                                                                                                                                                                                                     |                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                     | [**combinations**]{.ul} **of theory and observations**                                                                                                                                   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.i.c Why is a/are certain decision model(s) chosen?**                                                                                                                                                                                           | **Data (non-) availability, pattern-oriented modeling, reference to other studies, theoretical considerations**                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.i.d If the model / a submodel (e.g. the decision model) is based on empirical data, where does the data come from?**                                                                                                                           | **Participatory approaches (role playing games), household surveys, interviews, direct observations, statistical census, archives, GIS, field or lab experiments**                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.i.e At which level of aggregation were the data available?**                                                                                                                                                                                   | **Household / individual level, group level**                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Individual decision making.**

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.ii.a What are the subjects and objects of decision-making? On which level of aggregation is decision-making modeled? Are multiple levels of decision making included?** | **Name subjects (individuals agents / households, on communal level, top down decision maker) and objects of decisions, e.g.: Form of land use, distribution of labor, choices of buying and selling** |
+==============================================================================================================================================================================+========================================================================================================================================================================================================+
| **II.ii.b What is the basic rationality behind agents' decision-making in the model?** Do agents pursue an explicit objective or have other success criteria?                | **Rational choice (classical optimization approach, utility maximization), bounded rationality (satisficing approach), no objectives (routine based, trial and error)**                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.ii.c How do agents make their decisions?**                                                                                                                              | **Decision tree, utility function, random choice**                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.ii.d Do the agents adapt their behavior to changing endogenous and exogenous state variables? And if yes, how?**                                                        | **Adaption of resource extraction level in dependence of ecological state of resource**                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.ii.e Do social norms or cultural values play a role in the decision-making process?**                                                                                   | **Cultural norms, trust**                                                                                                                                                                              |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.ii.f Do spatial aspects play a role in the decision process?**                                                                                                          | **Space-theory based models**                                                                                                                                                                          |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.ii.g Do temporal aspects play a role in the decision process?**                                                                                                         | **Discounting, memory**                                                                                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **II.ii.h To which extent and how is uncertainty included in the agents' decision rules?**                                                                                   | **Not at all / stochastic elements mimic uncertainties in agents' behavior / agents explicitly consider uncertain situations or risk**                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Learning.**

| II.iii Learning \| II.iii.a Is individual learning included in the decision process? How do individuals change their decision rules over time as consequence of their experience? \| **Change of aspiration levels depending on past experiences** \|

\|----------------------------------------------------\|----------------------------------------------------------------------------\|------------------------------------------------------\| \| **II.iii.b\
Is collective learning implemented in the model?** \| **Evolution,\
genetic algorithms** \| \|

**Individual sensing.**

| **II.iv Individual** Sensing \| II.iv.a What **endogenous** and **exogenous** state variables are individuals assumed to sense and consider in their decisions? **Is the sensing process erroneous?** \|   \|

\|----------------------------------------------------------------------------------------------\|----------------------------------------------------------------------------------------------------\|-----\| \| II.iv.b What state variables\
of which other individuals can an individual perceive? **Is the sensing process erroneous?** \| **(Multiple)\
resources (including working power, monetary resources, other income\
resources) and behavior of other agents** \| \| \| II.iv.c What is the spatial\
scale of sensing? \| Local, network, global\
(whole model space) \| \| \| II.iv.d Are the mechanisms\
by which agents obtain information modeled explicitly, or are individuals\
simply assumed to know these variables? \| Sensing is often assumed to\
be local, but can happen through networks or can even be assumed to be\
global. \| \| \| **II.iv.e\
Are costs for cognition and costs for gathering information inclu­ded in the\
model?** \|   \| \|

**Individual prediction.**

| **II.v.a Which data uses the agent to predict future conditions?** \| **Extrapolation from experience, from spatial observations** \|

\|------------------------------------------------------------------------------------\|---------------------------------------------------\| \| II.v.b What internal models\
are agents assumed to use to estimate future conditions or consequences of\
their decisions? \| \| \| **II.v.c\
Might agents be erroneous in the prediction process, and how is it  implemented?** \| **(External)\
uncertainty, (internal) capability of the agent** \|

Interaction.

 

| II.vi Interaction \| II.vi.a Are interactions among agents and entities assumed as direct or indirect? \| Direct interactions, indirect interactions (mediated by the environment / **the market, auction)** \|

\|----------------------------------------------------------------------------------------------------------------------------------\|-------------------------------------------------------------------------\|-------------------------------------------------------------------------------\| \| **II.vi.b\
On what do the interactions depend?** \| **Spatial\
distances (neighborhood), networks, type of agent** \| \| \| II.vi.c If the interactions\
involve communication, how are such communications represented? \| **Explicit\
messages (Matthews et al., 2007)** \| \| \| **II.vi.d\
If a coordination network exists, how does it affect the agent behaviour? Is the structure of the network imposed or emergent?** \| Centralized vs.\
decentralized, group based tasks \| \|

Collectives.

| II.vii Collectives \| II.vii.a Do the individuals form or belong to aggregations that affect, and are affected by, the individuals? Are these aggregations imposed by the modeller or do they emerge during the simulation? \| Social groups, human networks and organizations \|

\|------------------------------\|-------------------------------------------------------------------------------\|----------------------------\| \| II.vii.b How are collectives represented? \| Collective as emergent\
property vs. as a definition by the modeler (separate kind of entity with its\
own state variables and traits) \| \|

**Heterogeneity.**

| **II.viii.a Are the agents heterogeneous? If yes, which state variables and/or processes differ between the agents?** \| **Would an exchange of one agent with another at the beginning have an effect on the simulation?** \|

\|-------------------------------------------------------------------------------\|------------------------------------------------------------------------------\| \| **II.viii.b\
Are the agents heterogeneous in their decision-making? If yes, which decision\
models or decision objects differ between the agents?** \| \|

**Stochasticity.**

+---------------------+-------------------------------------------------------------------------------------------------------------+
| II.ix Stochasticity | II.ix.a What processes (including initialization) are modeled by assuming they are random or partly random? |
|                     |                                                                                                             |
|                     |                                                                                                             |
+---------------------+-------------------------------------------------------------------------------------------------------------+

+=====================+==============================================================================+ +---------------------+------------------------------------------------------------------------------+

**Observation.**

| II.x Observation \| II.x.a What data are collected from the ABM for testing, understanding, and analyzing it, and how and when are they collected? \|

\|----------------------------------------------------------------------------\|------------------------------------------------------------------------------\| \| II.x.b What key results,\
outputs or characteristics of the model are emerging from the individuals?\
(Emergence) \| \|

**2.2.3. Details**

**Implementation details.**

| **III.i.a How has the model been implemented?** \| **Computer system, programming language / simulation platform, simulation runtime, development time** \|

\|--------------------------------------------\|-------------------------------------------------------------------------\| \| **III.i.b\
Is the model accessible and if so where?** \| **Homepage?(link)** \|

**Initialisation.**

| III.ii.a What is the initial state of the model world, i.e. at time t=0 of a simulation run? \| Types and numbers of entities including the agents themselves, values / random distribution of their state variables \|

\|-----------------------------------------------------------------\|---------------------------------------------------------------------------\| \| III.ii.b Is initialization\
always the same, or is it allowed to vary among simulations? \|   \| \| III.ii.c Are the initial\
values chosen arbitrarily or based on data? \| References to data if any, **stakeholder choice** \|

Input data

+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
| III.iii.a Does the model use input from external sources such as data files or other models to represent processes that change over time? | Observed time series e.g. annual rainfall, time series generated by other models, |
|                                                                                                                                           |                                                                                   |
|                                                                                                                                           | [not]{.ul}: parameter values, initial values of state variables                   |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+

+=============================================================================+=========================================================+ +-----------------------------------------------------------------------------+---------------------------------------------------------+

**Submodels**

| III.iv.a What, in detail, are the submodels that represent the processes listed in 'Process overview and scheduling'? \| Equations, algorithms, additional information \|

\|----------------------------------------------------------------------------\|------------------------------------------------------------------------------\| \| III.iv.b What are the model\
parameters, their dimensions and reference values? \| Tables of parameters \| \| III.iv.c How were submodels\
designed or chosen, and how were they parameterized and then tested? \| Justifications, references\
to literature, independent implementation, testing, calibration, analysis of\
submodels \|

This is not to suggest that we believed only a single gene influenced handedness, but rather we focused on a single hypothetical gene as a means of exploring how any genetic variation would respond to selection.

Parameter justifications:

Number of spouses: 2

Differering RS for monogamy / polygamy:

Follows logic that If men contribute heavily to the upbringing and/or inheritance of individual children, polygyny will be costly and increases in RS will not be linear (brown et al., 2009)

Diminishing returns to reproductive success from multiple spouses (Borgerhoff Mulder & Ross, 2019)

Pimbwe: Men don't benefit linearly from multiple partners (Borgerhoff Mulder, 2009)

Rural ethiopia: One wife - mean children 4.75. two wives - mean children 6 (3 per wife) (seems to reflect lower reproductive success to second rank cowives specifically) (gibson & mace, 2006)

# 3. Results

# 4. Discussion

## 4.1. General discussion

In reality, we might expect a pattern similar to that of handedness - a universal preference for polyygyny, modified by cultural inheritance

## 4.2. Limitations

Doesn't leave enough room for flexible strategies [@noe2017]

Counter point: Marriage practices may be expected to be labile traits changing rapidly with ecological conditions, but our reconstructions actually suggest that these traits may change slowly over time, at least for hunter-gatherers in the absence of pressure from neighboring agriculturalists. from Walker et al (2011)

Does behaviour represent flexible strategies or stated norms? du & mace 2018

Durham ([1991](https://www.journals.uchicago.edu/doi/full/10.1086/700767#rf20)) argued that Boyd and Richerson's approach is based on a "radical individualism" that fails to recognize that cultural variants are often "imposed" on people regardless of their individual decisions. Fracchia and Lewontin ([2005](https://www.journals.uchicago.edu/doi/full/10.1086/700767#rf22)) raised a similar challenge, suggesting that the success of a variant is often determined by the degree of *power* backing it. With power, a ruler can impose beliefs or practices on a whole population by diktat, rendering all of the forces represented in cultural evolutionary models irrelevant. It is argued here, based on work by Boehm ([1999](https://www.journals.uchicago.edu/doi/full/10.1086/700767#rf5), [2012](https://www.journals.uchicago.edu/doi/full/10.1086/700767#rf6)), that, from at least the time of the early Middle Paleolithic, human bands were controlled by powerful *coalitions of the majority* that deliberately guided the development of moral norms to promote the common good. Cultural evolutionary models of the evolution of morality have been based on false premises. However, Durham ([1991](https://www.journals.uchicago.edu/doi/full/10.1086/700767#rf20)) and Fracchia and Lewontin's ([2005](https://www.journals.uchicago.edu/doi/full/10.1086/700767#rf22)) challenge does not undermine cultural evolutionary modeling in *nonmoral* domains. BUT leader following may actually assist the evolution of cooperation norms

Mating control may be unevenly distributed

## 4.3. Future directions

## 4.4. Summary

## References
